/*
 * Copyright 2016 Google Inc. All Rights Reserved.

 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at

 * http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#version 450
#extension GL_ARB_shading_language_420pack : enable
#extension GL_ARB_compute_shader : enable

layout(constant_id = 0) const int num_elements = 10;

layout(std140, binding = 0) uniform inputs {
        float input_values[num_elements];
};

layout(std430, binding = 1) buffer outputs {
        float output_values[num_elements];
};

layout (local_size_x = 16, local_size_y = 1) in;
void main() {
  const uint index = gl_LocalInvocationIndex;
  //output_values[index] = 2.0 * (1 + int(index));
  output_values[index] = 2.0 * input_values[index];
}

