/*
* Copyright 2016 Google Inc. All Rights Reserved.

* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at

* http://www.apache.org/licenses/LICENSE-2.0

* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef VCC_KEYDOWN_H_
#define VCC_KEYDOWN_H_

namespace vcc {

enum keycode_type {
#ifdef WIN32
	// TODO(gardell): Add more keycodes, also these are from WINAPI, some might not be relevant on all platforms.
	keycode_back = VK_BACK,
	keycode_tab = VK_TAB,
	keycode_clear = VK_CLEAR,
	keycode_return = VK_RETURN,
	keycode_shift = VK_SHIFT,
	keycode_control = VK_CONTROL,
	keycode_menu = VK_MENU,
	keycode_pause = VK_PAUSE,
	keycode_capital = VK_CAPITAL,
	keycode_kana = VK_KANA,
	keycode_hangul = VK_HANGUL,
	keycode_junja = VK_JUNJA,
	keycode_final = VK_FINAL,
	keycode_hanja = VK_HANJA,
	keycode_kanji = VK_KANJI,
	keycode_escape = VK_ESCAPE,
	keycode_convert = VK_CONVERT,
	keycode_nonconvert = VK_NONCONVERT,
	keycode_accept = VK_ACCEPT,
	keycode_modechange = VK_MODECHANGE,
	keycode_space = VK_SPACE,
	keycode_page_up = VK_PRIOR,
	keycode_page_down = VK_NEXT,
	keycode_end = VK_END,
	keycode_home = VK_HOME,
	keycode_left = VK_LEFT,
	keycode_up = VK_UP,
	keycode_right = VK_RIGHT,
	keycode_down = VK_DOWN,
	keycode_select = VK_SELECT,
	keycode_print = VK_PRINT,
	keycode_execute = VK_EXECUTE,
	keycode_snapshot = VK_SNAPSHOT,
	keycode_insert = VK_INSERT,
	keycode_delete = VK_DELETE,
	keycode_help = VK_HELP,
	keycode_0 = 0x30,
	keycode_1 = 0x31,
	keycode_2 = 0x32,
	keycode_3 = 0x33,
	keycode_4 = 0x34,
	keycode_5 = 0x35,
	keycode_6 = 0x36,
	keycode_7 = 0x37,
	keycode_8 = 0x38,
	keycode_9 = 0x39,
	keycode_a = 0x41,
	keycode_b = 0x42,
	keycode_c = 0x43,
	keycode_d = 0x44,
	keycode_e = 0x45,
	keycode_f = 0x46,
	keycode_g = 0x47,
	keycode_h = 0x48,
	keycode_i = 0x49,
	keycode_j = 0x4A,
	keycode_k = 0x4B,
	keycode_l = 0x4C,
	keycode_m = 0x4D,
	keycode_n = 0x4E,
	keycode_o = 0x4F,
	keycode_p = 0x50,
	keycode_q = 0x51,
	keycode_r = 0x52,
	keycode_s = 0x53,
	keycode_t = 0x54,
	keycode_u = 0x55,
	keycode_v = 0x56,
	keycode_w = 0x57,
	keycode_x = 0x58,
	keycode_y = 0x59,
	keycode_z = 0x5A,
	keycode_lwin = VK_LWIN,
	keycode_rwin = VK_RWIN,
	keycode_apps = VK_APPS,
	keycode_sleep = VK_SLEEP,
	keycode_numpad0 = VK_NUMPAD0,
	keycode_numpad1 = VK_NUMPAD1,
	keycode_numpad2 = VK_NUMPAD2,
	keycode_numpad3 = VK_NUMPAD3,
	keycode_numpad4 = VK_NUMPAD4,
	keycode_numpad5 = VK_NUMPAD5,
	keycode_numpad6 = VK_NUMPAD6,
	keycode_numpad7 = VK_NUMPAD7,
	keycode_numpad8 = VK_NUMPAD8,
	keycode_numpad9 = VK_NUMPAD9,
	keycode_multiply = VK_MULTIPLY,
	keycode_add = VK_ADD,
	keycode_separator = VK_SEPARATOR,
	keycode_subtract = VK_SUBTRACT,
	keycode_decimal = VK_DECIMAL,
	keycode_divide = VK_DIVIDE,
	keycode_f1 = VK_F1,
	keycode_f2 = VK_F2,
	keycode_f3 = VK_F3,
	keycode_f4 = VK_F4,
	keycode_f5 = VK_F5,
	keycode_f6 = VK_F6,
	keycode_f7 = VK_F7,
	keycode_f8 = VK_F8,
	keycode_f9 = VK_F9,
	keycode_f10 = VK_F10,
	keycode_f11 = VK_F11,
	keycode_f12 = VK_F12,
	keycode_f13 = VK_F13,
	keycode_f14 = VK_F14,
	keycode_f15 = VK_F15,
	keycode_f16 = VK_F16,
	keycode_f17 = VK_F17,
	keycode_f18 = VK_F18,
	keycode_f19 = VK_F19,
	keycode_f20 = VK_F20,
	keycode_f21 = VK_F21,
	keycode_f22 = VK_F22,
	keycode_f23 = VK_F23,
	keycode_f24 = VK_F24,
	keycode_numlock = VK_NUMLOCK,
	keycode_scroll = VK_SCROLL,
	keycode_browser_back = VK_BROWSER_BACK,
	keycode_browser_forward = VK_BROWSER_FORWARD,
	keycode_browser_refresh = VK_BROWSER_REFRESH,
	keycode_browser_stop = VK_BROWSER_STOP,
	keycode_browser_search = VK_BROWSER_SEARCH,
	keycode_browser_favorites = VK_BROWSER_FAVORITES,
	keycode_browser_home = VK_BROWSER_HOME,
	keycode_volume_mute = VK_VOLUME_MUTE,
	keycode_volume_down = VK_VOLUME_DOWN,
	keycode_volume_up = VK_VOLUME_UP,
	keycode_media_next_track = VK_MEDIA_NEXT_TRACK,
	keycode_media_prev_track = VK_MEDIA_PREV_TRACK,
	keycode_media_stop = VK_MEDIA_STOP,
	keycode_media_play_pause = VK_MEDIA_PLAY_PAUSE,
	keycode_launch_mail = VK_LAUNCH_MAIL,
	keycode_launch_media_select = VK_LAUNCH_MEDIA_SELECT
#endif // WIN32
};

}  // namespace vcc

#endif // VCC_KEYDOWN_H_